name: Spotlight
author: RuudBurger
category: Interface
tags: [mask, spotlight, fill]
docs: http://github.com/RuudBurger/Spotlight
demo: http://github.com/RuudBurger/Spotlight/raw/master/Source/Demo.html